temperature: 0.7  # Generation temperature
max_new_tokens: 500  # Max tokens per step
batch_size: 2  # Batch size for candidate generation (null = same as n)
sequential_generation: false  # Generate candidates one by one to save memory
top_p: 1.0
top_k: 50