# @package generation

n: 10  # Number of candidates per step
temperature: 0.7  # Generation temperature
max_new_tokens: 250  # Max tokens per step
max_steps: 30  # Maximum number of reasoning steps
batch_size: null  # Batch size for candidate generation (null = same as n)
sequential_generation: false  # Generate candidates one by one to save memory
