# @package _global_

defaults:
  - dataset: small_gsm8k
  - model: together_ai
  - generation: default
  - output: default
  - system: default
  - strategy: chain_of_thought
  - _self_

# Chain-of-thought doesn't need a scorer
scorer: null
verbose: true

# API-specific overrides
generation:
  max_new_tokens: 300  # Shorter for faster API calls