# @package _global_

defaults:
  - dataset: small_gsm8k
  - model: together_ai
  - generation: default
  - output: default
  - system: default
  - strategy: deep_think_confidence
  - _self_

# Override some settings for DeepConf API testing
verbose: true

# DeepConf doesn't need a scorer like ReasonEval
# It uses internal confidence-based filtering
scorer: null

# API-specific overrides for testing
strategy:
  num_paths: 8                    # Moderate number for API testing
  filtering_percentage: 0.6       # Keep top 60% (more selective)
  temperature: 0.8                # Higher temperature for diversity
  confidence_metric: "avg_confidence"
  mode: "offline"

generation:
  temperature: 0.8                # Should match strategy temperature
  max_new_tokens: 300             # Shorter for faster API calls

# Use smaller dataset for testing
dataset:
  subset: 20                      # Only 20 questions for testing