# @package _global_

defaults:
  - dataset: default
  - model: hf_qwen3
  - generation: default
  - output: default
  - system: default
  - _self_

# Main configuration
scorer:
  type: prm
  #model_path: "GAIR/ReasonEval-7B"
  model_path: "Qwen/Qwen2.5-Math-7B-PRM800K"
  device: cuda:1
  batch_size: 1

evaluator:
  base_url: https://openrouter.ai/api/v1
  model: deepseek/deepseek-r1-0528
  n_threads: 1

strategy:
  type: online_best_of_n
  candidates_per_step: 3
  max_steps: 3