# @package _global_

defaults:
  - dataset: default
  - model: hf_qwen3
  - generation: default
  - output: default
  - system: default
  - scorer: prm
  - _self_

evaluator:
  base_url: https://openrouter.ai/api/v1
  model: deepseek/deepseek-r1-0528
  n_threads: 1
  prompt_file: ""

strategy:
  type: online_best_of_n
  candidates_per_step: 3
  max_steps: 3