# @package _global_

hydra:
  run:
    dir: ${save_dir}/eval/${now:%Y-%m-%d}/${now:%H-%M-%S}

save_dir: "./workdir"  # Directory to save results (will create validity/redundancy subdirs)

defaults:
  - dataset: default
  - model: hf_qwen3
  - generation: default
  - system: default
  - scorer: uncertainty
  - evaluation/llm_judge: default
  - evaluation/alignscore: default
  - _self_

evaluation:
  evaluators: [llm_judge, exact_match]

strategy:
  type: phi_decoding
  candidates_per_step: 3
  max_steps: 5
  cluster_num: 2

report_to: wandb