# @package _global_

defaults:
  - dataset: default
  - model: default
  - generation: default
  - output: default
  - system: default
  - _self_

# Main configuration
verbose: false


scorer:
  type: reasoneval_direct
  model_path: "GAIR/ReasonEval-7B"
  device: cuda:1
  batch_size: 1

evaluator:
  base_url: https://api.deepseek.com/v1
  model: deepseek-reasoner
  n_threads: 1

strategy:
  type: direct_online_best_of_n_reason_eval_separate
  candidates_per_step: 3
  max_steps: 3