# @package _global_

defaults:
  - dataset: default
  - model: hf_qwen3
  - generation: default
  - output: default
  - system: default
  - scorer: prm
  - evaluation/llm_judge: default
  - evaluation/alignscore: default
  - _self_

evaluation:
  evaluators: [llm_judge, exact_match, alignscore]

strategy:
  type: online_best_of_n
  candidates_per_step: 3
  max_steps: 3
