# @package _global_

defaults:
  - dataset: default
  - model: default
  - generation: default
  - output: default
  - system: default
  - _self_

# Main configuration
verbose: false


scorer:
  type: reasoneval_direct
  model_path: "GAIR/ReasonEval-7B"
  device: cuda
  batch_size: 1
  

strategy:
  type: direct_online_best_of_n_reason_eval_separate
  candidates_per_step: 10
  max_steps: 20