defaults:
  - dataset: gsm8k
  - provider: openrouter/default  
  - strategy: test_minimal
  - prompts: default

dataset:
  subset_frac: 0.001

provider:
  type: openrouter
  model: deepseek/deepseek-r1-0528-qwen3-8b
  api_key: "OPENROUTER_API_KEY"
 
prompt_paths:
  gsm8k:
    base: config/prompts/gsm8k_base_prompt.txt
    # cot: config/prompts/gsm8k_cot_prompt.txt
    cot: config/prompts/qwen3_prompt.txt
  
strategy:
  candidates_per_step: 2
  max_steps: 5
  max_new_tokens: 512
  temperature: 0.5
  uncertainty_metric: pd
  uncertainty_threshold: 0.20
  uncertainty_top_k: 2

output:
  out_path: test_single_result.jsonl

system:
  seed: 42

# Configure step markers here instead of a separate group
step_marker_patterns:
  - "## Step {n}:"
  - "Step {n}:"
  - "- Step {n}:"
