# @package _global_

defaults:
  - dataset: gsm8k
  - provider: together/default  
  - step_markers: default
  - strategy: test_minimal

dataset:
  subset_frac: 0.002

run:
  methods: ['base', 'uncert']

base_generation:
  temperature: 0.0
  max_new_tokens: 1024
  n: 1

provider:
  type: together
  api_key: "TOGETHER_API_KEY"

model:
# model: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
  model_name: Qwen/Qwen2.5-7B-Instruct-Turbo
  eos_token: <|endoftext|>

output:
  run_id: test_50_newUncert_v2
 
prompt_paths:
  gsm8k:
    base: config/prompts/uncert_cot_short_prompt.txt
    cot: config/prompts/uncert_cot_short_prompt.txt
  
strategy:
  candidates_per_step: 3
  max_steps: 30
  max_new_tokens: 256
  temperature: 0.7
  uncertainty_metric: pd
  uncertainty_threshold: 0.3
  uncertainty_top_k: 2

verification:
  enabled: true
  model: deepseek-ai/DeepSeek-V3.1
  n: 1
  temperature: 1.0
  max_new_tokens: 256
  stop: ["<|endoftext|>"]
  prompt_template_path: config/prompts/annotator_prompt.txt

system:
  seed: 42

