# @package dataset

dataset_path: "gsm8k"  # Dataset to evaluate on (HuggingFace name or local path)
dataset_split: "test"  # Dataset split to use
subset: null  # Only process first N samples from dataset (null for all)
prompt_file: null  # Path to prompt template file (optional)
