name: Lint

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Check formatting with black
        run: black --check llm_tts scripts

      - name: Check import sorting with isort
        run: isort --check-only --profile black llm_tts scripts

      - name: Lint with flake8
        run: flake8 llm_tts scripts

      - name: Test with pytest
        run: |
          pytest tests/online_best_of_n tests/run_tts_eval
